### ISSUE TITLE
This is not a primality test

### ISSUE THREAD

**Issue by simonepri** [lukeed/primeval#1]
These are the fastest known algorithms:
[https://en.wikipedia.org/wiki/Primality_test#Fast_deterministic_tests](https://en.wikipedia.org/wiki/Primality_test#Fast_deterministic_tests)

The video states:
> what we actually managed to prove is that all numbers which don't have 2 or 3 as factor, if you square them, you get a number that is one more of a multiple of 24.

Proof of the fact that does not work:
```js
primeval(77);
// => true but 77 = 11*7
```

Please remove it before people may think that this is correct.

**Comment by arguiot** [comment]
👍 .

P.S. @lukeed if you want a fast primality test, you can check out the code I wrote with https://github.com/arguiot/TheoremJS in the `src` folder.

**Comment by simonepri** [comment]
> fast primality test

I would rather not call "fast" something that is exponential but it is perfectly fine for numbers up to `Number.MAX_SAFE_INTEGER`.
I think there are even better tests when dealing with fixed size numbers.

**Comment by arguiot** [comment]
@simonepri I’m sure there are, but if this lib can achieve that it would be ok then.

I believe the best option would be to write a test using C or something else and compile it to WebAssemby

**Comment by lukeed** [comment]
Hey thanks! You are right – I definitely misunderstood the video. Of course it can't be that easy... 😅 I will be deprecating this `1.0.0` version and putting out another solution (since npm packages can't be deleted) based on an algorithm I know I _can_ implement.

**Comment by simonepri** [comment]
> "since npm packages can't be deleted"

You can `npm unpublish` until 48 hours after the first `npm publish` if I don't remember wrong.

**Comment by lukeed** [comment]
I will be publishing a version tonight based on AKS, which is 100% correct and not a probable prime test.

**Comment by simonepri** [comment]
@lukeed Even though AKS is asymptotically better than the naive solution, it is really complicate to implement and probably slower for the most use cases (At least if we are dealing with just 53 bits numbers) due to higher constant factors.

**Comment by lukeed** [comment]
Yup, but at least it's something. I also did not find anything tagged with "AKS" on npm so will be unique if nothing else. 😄

**Comment by simonepri** [comment]
I think [this](https://www.cs.cmu.edu/afs/cs/user/mjs/ftp/thesis-program/2005/rotella.pdf) is a good starting point.
It will be definitely interesting having it implemented in JS.

**Comment by lukeed** [comment]
@simonepri implemented a version of AKS (the core, coefficient tracking & modulo). It's slow as shit tho 😆 Somewhere down the road I'll do a 3.0 with Fermat's or something else... probabilistic, but usable.
